# Generated by Django 5.2 on 2025-05-19 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='contenido',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='fecha_publicacion',
        ),
        migrations.RemoveField(
            model_name='post',
            name='titulo',
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='Urie', max_length=100),
            preserve_default=False,
        ),
    ]
